@url = http://localhost:8080/api/V1

# Buscar aluno por e-mail
GET {{url}}/aluno?rg=123456789 HTTP/1.1

# Adicionar 
POST {{url}}/aluno HTTP/1.1
Content-Type: application/json

{
  "nome": "Luiz",
  //"bolsaFamilia": true, -> valor default "false"
  //"auxilioBrasil": false, -> valor default "false"
  "imovel": "CEDIDO",
  "numerosDePessoasNaCasa": 4,
  "contribuintesDaRendaFamiliar": 2,
  //"alunoContribuiParaRenda": true, -> valor default "false"
  "rendaFamiliarEmSalariosMinimos": 3,
  "transporte": "PEDESTRE",
  //"vemAcompanhado": false, -> valor default "false"
  "turno": "MANHA",
  "dataPreenchimento": "2023-01-01T12:00:00",
  "cidade": "City",
  "estado": "State",
  "rg": "123456789",
  "cpfResponsavel": "123.456.789-01"
  //"faltas": 2, -> valor default 0
  //"status": true -> valor default "true"
}