@url = https://projeto-bushido-backend.onrender.com/api/V1/admin
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzZWNyZXQiLCJlbWFpbCI6InN1cGVyX2FkbWluQGVtYWlsLmNvbS5iciIsInN1YiI6InN1cGVyX2FkbWluQGVtYWlsLmNvbS5iciIsImV4cCI6MTcxMTExODUyMH0.ueGedfb38jVkQnwFezE8RPEaLakQ-XHTB5qQlHH9pHU

POST {{url}}/signup HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Super Admin",
    "email":"super_admin1@email.com.br",
    "cargo":"Administrador",
    "senha": "123456",
    "role": "USER"
}

###
POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "super_admin@email.com.br",
    "senha": "123456"
}