@url = https://projeto-bushido-backend.onrender.com/api/V1/admin
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIxZTJhNDNiMDYwOTBkZjMzYjUyMjg3ZDAzN2NjNjM2ZSIsImVtYWlsIjoic3VwZXJfYWRtaW5AZW1haWwuY29tLmJyIiwic3ViIjoic3VwZXJfYWRtaW5AZW1haWwuY29tLmJyIiwiZXhwIjoxNzA5MzM4OTI2fQ.ckjgD1RYJMmvWUWOp1SO5HNqnJY7bYBItlrg3wEsp8E

POST {{url}}/signup HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Super Admin",
    "email":"super_admin1@email.com.br",
    "cargo":"Administrador",
    "senha": "123456",

}

###
POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "super_admin@email.com.br",
    "senha": "123456"
}