@url = http://localhost:8080/api/V1/aluno

# Buscar aluno por e-mail
GET {{url}}?rg=123456789 HTTP/1.1

# Adicionar
### 
POST {{url}} HTTP/1.1
Content-Type: application/json

{
  "nome": "Luiz",
  "genero": "M",
  "dataNascimento": "2023-01-01",
  "dadosSociais":{
    "bolsaFamilia": true,
    "auxilioBrasil": false,
    "imovel": "CEDIDO",
    "numerosDePessoasNaCasa": 4,
    "contribuintesDaRendaFamiliar": 2,
    "alunoContribuiParaRenda": true,
    "rendaFamiliarEmSalariosMinimos": 3
  },
   "dadosEscolares": {
    "turno": "MANHA",
    "escola": "E.M.E.F Marechal Rondon",
    "serie": 6
  },
  "dataPreenchimento": "2023-01-01T12:00:00",
  "endereco":{
    "cidade": "City",
    "estado": "State",
    "cep":"06000142",
    "numero":"100"
  },
  "rg": "123456789",
  "responsaveis": [
      {
      "nome":"Teste 00",
      "cpf": "123.456.789-01",
      "telefone":"0000-0000",
      "email":"email@email.com",
      "filiacao":"PAI"
      }
    ],
   "graduacao": {
        "kyu": 7,
        "frequencia": 75
    },
    "historicoSaude": {
    "tipoSanguineo": "A_POSITIVO",
    "fatorRh": "POSITIVO",
    "usoMedicamentoContinuo": {
      "resposta": "",
      "qualMedicamento": ""
    },
    "cirurgia": {
      "resposta": "",
      "tipo": ""
    },
    "alergia": {
      "resposta": "",
      "tipo": ""
    },
    "doencaCronica": {
      "resposta": "",
      "tipo": ""
    },
    "deficiencia":["Nenhuma"],
    "acompanhamentoSaude":["Nenhum"]
  }
}

###
PATCH {{url}}/adicionarFalta/123456789 HTTP/1.1
Content-Type: application/json

{
  "motivo":"Aluno se encontra doente",
  "observacao":"luis trouxe atestado"
}

###
PATCH {{url}}/retirarFalta/123456789?data=27-01-2024 HTTP/1.1

###
POST {{url}}/adicionarResponsavel/123456789 HTTP/1.1
Content-Type: application/json

{
  "nome": "Teste",
  "cpf": "020202020201",
  "telefone": "123456789",
  "email": "email@email.com.br",
  "filiacao": "MAE"
}

###
DELETE {{url}}/removerResponsavel/123456789?cpf=020202020201 HTTP/1.1