@url = http://0.0.0.0:8080/api/V1/admin
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzZWNyZXQiLCJlbWFpbCI6InN1cGVyX2FkbWluQGVtYWlsLmNvbS5iciIsInN1YiI6InN1cGVyX2FkbWluQGVtYWlsLmNvbS5iciIsImV4cCI6MTcxMDg3MTUzMH0.uKlHc75WWzmvXq7Q8baaBwJnT3NQ4GorvFE79_wV-TI

POST {{url}}/signup HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{"nome": "Zé do Pipo", "email": "ze@email.com.br", "cargo": "professor", "senha": "123456", "role": "USER"}

###
POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "super_admin@email.com.br",
    "senha": "123456"
}