@url = http://0.0.0.0:8080/api/V1/aluno
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmZTIzcmYyMzlVSjd0amg3ODZmN0c3VDZGNTZHRlI3R0Y1Nkc2Zmc2N2Y2Zzd5Z3ZGUjVERjdndDY3OGpva2kwOThVNzg5SiIsImVtYWlsIjoic3VwZXJfYWRtaW5AZW1haWwuY29tLmJyIiwic3ViIjoic3VwZXJfYWRtaW5AZW1haWwuY29tLmJyIiwiZXhwIjoxNzA5MzQ2NDc3fQ.reacAL6ugGB4T22kCklPDalkSZkxmj1jCa73Zp28onE

# Buscar aluno por e-mail
GET {{url}}?rg=123456789 HTTP/1.1
Authorization: Bearer {{token}}
###
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Luiz",
  "genero": "M",
  "dataNascimento": "2022-15-01",
  "dadosSociais":{
    "imovel": "CEDIDO",
    "rendaFamiliarEmSalariosMinimos": 3
  },
  "dadosEscolares": {
    "turno": "MANHA"
  },
  "dataPreenchimento": "2023-01-01T12:00:00",
  "endereco":{
    "cep":"06000142",
    "numero":"100"
  },
  "rg": "123456789",
  "responsaveis": [
      {
      "nome":"Joaquim",
      "cpf":"12345678901",
      "telefone":"0000-0000",
      "filiacao":"PAI"
      }
    ],
   "graduacao": {
        "kyu": 7,
        "frequencia": 75
    },
    "historicoSaude": {
    "tipoSanguineo": "A_POSITIVO",
    "fatorRh": "POSITIVO",
    "usoMedicamentoContinuo": {
      "resposta": "",
      "qualMedicamento": ""
    },
    "cirurgia": {
      "resposta": "",
      "tipo": ""
    },
    "alergia": {
      "resposta": "",
      "tipo": ""
    },
    "doencaCronica": {
      "resposta": "",
      "tipo": ""
    }
  }
}

###
POST {{url}}/adicionarFalta/123456789 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "motivo":"Aluno se encontra doente",
  "observacao":"luis trouxe atestado"
}

###
POST {{url}}/adicionarFalta/123456789/1506992087893 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "motivo":"Aluno se encontra doente",
  "observacao":"luis trouxe atestado"
}

###
DELETE {{url}}/retirarFalta/123456789?data=02-08-2014 HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{url}}/adicionarResponsavel/123456789 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Teste",
  "cpf": "020202020202",
  "telefone": "123456789",
  "filiacao": "MAE"
}

###
DELETE {{url}}/removerResponsavel/123456789?cpf=020202020202 HTTP/1.1
Authorization: Bearer {{token}}
###
POST {{url}}/deficiencia/123456789?deficiencia=amidalite HTTP/1.1
###
DELETE {{url}}/deficiencia/123456789?deficiencia=aaa HTTP/1.1
###
POST {{url}}/acompanhamentoSaude/123456789?acompanhamento=aaa HTTP/1.1
Authorization: Bearer {{token}}
###
DELETE {{url}}/acompanhamentoSaude/123456789?acompanhamento=aaa HTTP/1.1
Authorization: Bearer {{token}}

###
PUT {{url}}/historicoSaude/123456789 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "alergias": {
      "tipo": "p",
      "resposta": true
    }
}