@url = http://0.0.0.0:8080/api/V1/aluno
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzZWNyZXQiLCJlbWFpbCI6InN1cGVyX2FkbWluQGVtYWlsLmNvbS5iciIsInN1YiI6InN1cGVyX2FkbWluQGVtYWlsLmNvbS5iciIsImV4cCI6MTcxMjUyMjg0N30.bSC8sgj6Ntv7XfEIa00SIwtXDjyH17JaMcSEDLNHb4M
@rg=123456789

GET {{url}}?nome=Zé HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{url}}?rg={{rg}} HTTP/1.1
Authorization: Bearer {{token}}
###
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Zé da Manga",
  "sobrenome": "a zé do pipo",
  "genero": "M",
  "dataNascimento": "2020-03-20",
  "turma":"Fundao I",
  "dadosSociais": {
    "bolsaFamilia": true,
    "auxilioBrasil": true,
    "imovel": "PROPRIO",
    "numerosDePessoasNaCasa": 12,
    "contribuintesDaRendaFamiliar": 3,
    "alunoContribuiParaRenda": true,
    "rendaFamiliarEmSalariosMinimos": 2000
  },
  "dadosEscolares": {
    "turno": "MANHA",
    "escola": "Emef Luis Ziraldo",
    "serie": 4
  },
  "endereco": {
    "estado": "São Paulo",
    "cidade": "Osasco",
    "cep": "06140140",
    "numero": 565
  },
  "rg": "000000000",
  "responsaveis": [
    {
      "nome": "Otavio Benedicto Domingues",
      "cpf": "45916466880",
      "telefone": "11972300768",
      "email": "otavio.w@outlook.com",
      "filiacao": "MAE"
    }
  ],
  "graduacao": {
    "kyu": 4
  },
  "historicoSaude": {
    "tipoSanguineo": "A_POSITIVO",
    "fatorRh": "POSITIVO",
    "usoMedicamentoContinuo": {
      "resposta": "",
      "tipo": "dd"
    },
    "cirurgia": {
      "resposta": false,
      "tipo": ""
    },
    "alergia": {
      "resposta": false,
      "tipo": "dd"
    },
    "doencaCronica": {
      "resposta": false,
      "tipo": ""
    },
    "deficiencia": [],
    "acompanhamentoSaude": []
  }
}


###
POST {{url}}/falta/{{rg}}/1711940400000 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "motivo":"Aluno se encontra doente",
  "observacao":"luis trouxe atestado"
}
###
DELETE {{url}}/falta/{{rg}}?data=01-04-2024 HTTP/1.1
Authorization: Bearer {{token}}

###
PUT {{url}}/{{rg}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "dadosEscolares": {
    "turno": "MANHA"
  }
}

###
POST {{url}}/responsavel/{{rg}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Teste",
  "cpf": "45202055636",
  "telefone": "11999999999",
  "filiacao": "PAI"
}

###
DELETE {{url}}/responsavel/{{rg}}?cpf=45202055636 HTTP/1.1
Authorization: Bearer {{token}}
###
POST {{url}}/deficiencia/123456789?deficiencia=fff HTTP/1.1
Authorization: Bearer {{token}}
###
DELETE {{url}}/deficiencia/123456789?deficiencia=fff HTTP/1.1
Authorization: Bearer {{token}}
###
POST {{url}}/acompanhamentoSaude/123456789?acompanhamento=fffff HTTP/1.1
Authorization: Bearer {{token}}
###
DELETE {{url}}/acompanhamentoSaude/123456789?acompanhamento=aaa HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{url}}/graduacao/{{rg}}/aprovar HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{url}}/graduacao/{{rg}}/reprovar HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


