@url = http://0.0.0.0:8080/api/V1/aluno
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzZWNyZXQiLCJlbWFpbCI6InN1cGVyX2FkbWluQGVtYWlsLmNvbS5iciIsInN1YiI6InN1cGVyX2FkbWluQGVtYWlsLmNvbS5iciIsImV4cCI6MTcxMDg2Mjc5NX0.6D8yi4Gsvs7pYuTt2SVF4kCmJosTqDNwU_XRz49B5t0

@rg=012345678

# Buscar aluno por e-mail
GET {{url}}?rg={{rg}} HTTP/1.1
Authorization: Bearer {{token}}
###
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Luiz",
  "genero": "M",
  "dataNascimento": "2010-10-05",
  "dadosSociais":{
    "imovel": "CEDIDO",
    "rendaFamiliarEmSalariosMinimos": 3,
    "bolsaFamilia":true,
    "auxilioBrasil":true,
    "numerosDePessoasNaCasa":4
  },
  "dadosEscolares": {
    "turno": "MANHA"
  },
  "dataPreenchimento": "2023-01-01T12:00:00",
  "endereco":{
    "cep":"06000142",
    "numero":"100"
  },
  "rg": "012345678",
  "responsaveis": [
      {
      "nome":"Joaquim",
      "cpf":"12345678901",
      "telefone":"0000-0000",
      "filiacao":"PAI"
      }
    ],
   "graduacao": {
      "kyu": 7,
      "frequencia": 75
    },
    "historicoSaude": {
      "tipoSanguineo": "A_POSITIVO",
      "fatorRh": "POSITIVO"
  }
}

###
POST {{url}}/adicionarFalta/{{rg}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "motivo":"Aluno se encontra doente",
  "observacao":"luis trouxe atestado"
}

###
POST {{url}}/adicionarFalta/{{rg}}/1326992087893 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "motivo":"Aluno se encontra doente",
  "observacao":"luis trouxe atestado"
}
###
DELETE {{url}}/retirarFalta/{{rg}}?data=22-07-2021 HTTP/1.1
Authorization: Bearer {{token}}

###
PUT {{url}}/012345678 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome":"Oliverinha",
  "genero":"F",
  "dadosEscolares": {
    "turno": "TARDE"
  }
}


###
###
POST {{url}}/adicionarResponsavel/{{rg}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Teste",
  "cpf": "00045678901",
  "telefone": "11999999999",
  "filiacao": "PAI"
}

###
DELETE {{url}}/removerResponsavel/{{rg}}?cpf=00045678901 HTTP/1.1
Authorization: Bearer {{token}}
###
POST {{url}}/deficiencia/123456789?deficiencia=amidalite HTTP/1.1
Authorization: Bearer {{token}}
###
DELETE {{url}}/deficiencia/123456789?deficiencia=amidalite HTTP/1.1
Authorization: Bearer {{token}}
###
POST {{url}}/acompanhamentoSaude/123456789?acompanhamento=aaa HTTP/1.1
Authorization: Bearer {{token}}
###
DELETE {{url}}/acompanhamentoSaude/123456789?acompanhamento=aaa HTTP/1.1
Authorization: Bearer {{token}}

###
PUT {{url}}/historicoSaude/012345678 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "alergia": {
      "resposta": true,
      "tipo": "dij9-qwdjqh"
    }
}