@url = http://0.0.0.0:8080/api/V1/turma
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzZWNyZXQiLCJlbWFpbCI6InN1cGVyX2FkbWluQGVtYWlsLmNvbS5iciIsInN1YiI6InN1cGVyX2FkbWluQGVtYWlsLmNvbS5iciIsImV4cCI6MTcxMjM2OTM0Nn0.uubMaZqNadXe97TAlYdQAqeriL9L2xyhyWNmhxqNuwg
@rg=123456789

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome":"Fundão I",
    "endereco": "Rua Almir Juca",
    "tutor": "Luiz Roberto"
}

###
DELETE {{url}}/Fundão I HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{url}}/aluno/Fundão I HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "nicolas souza",
  "genero": "M",
  "dataNascimento": "2008-05-08",
  "rg":"165787777"
}

###
GET {{url}} HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{url}}/Fundão I HTTP/1.1
Authorization: Bearer {{token}}