@url = http://0.0.0.0:8080/api/V1/turma
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzZWNyZXQiLCJlbWFpbCI6InN1cGVyX2FkbWluQGVtYWlsLmNvbS5iciIsInN1YiI6InN1cGVyX2FkbWluQGVtYWlsLmNvbS5iciIsImV4cCI6MTcxMjg4OTc5MX0.hYGcuZolZ37X1CmSkmdKLjx-9nFLsAC1j_hmlnK1688
@rg=123456789

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome":"Fundão I",
    "endereco": "Rua Almir Juca",
    "tutor": "Luiz Roberto"
}

###
DELETE {{url}}/Fundão I HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{url}}/Fundão I/aluno HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "nicolas souza",
  "genero": "M",
  "dataNascimento": "2008-05-08",
  "rg":"000000000"
}

###
GET {{url}} HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{url}}/Fundão I HTTP/1.1
Authorization: Bearer {{token}}

###
DELETE {{url}}/Fundão I/aluno/{{rg}} HTTP/1.1
Authorization: Bearer {{token}}